// Generated by npm run generate:contract. Do not edit.
export const DRAFT_SCHEMA_VERSION = "1.8";
export const SEASON_SCHEMA_VERSION = "1.4";

export interface DraftView {
  schema_version: string;
  generated_at: number;
  league: LeagueSummary;
  draft: DraftStatus;
  my_roster: TeamRoster | null;
  rosters: Array<TeamRoster>;
  draft_projections: Array<TeamProjection>;
  available: Array<AvailablePlayer>;
  tier_alerts: Array<TierAlert>;
  position_run: PositionRun | null;
  recommendations: Array<Recommendation>;
  recent_picks: Array<RecentPick>;
  replacement_baselines: Record<string, number>;
  replacement_demand: Record<string, number>;
  pick_prices: Array<PickPrice>;
  data_health: DataHealth;
}

export interface AvailablePlayer extends BoardPlayer {
  survival_next: number | null;
}

export interface BoardPlayer {
  player_id: string;
  name: string;
  position: string;
  team: string | null;
  bye_week: number | null;
  points: number;
  bonus_points: number;
  vorp: number;
  tier: number;
  position_rank: number;
  overall_rank: number;
  adp: number | null;
  injury_status: string | null;
  sleeper_pts_ppr: number | null;
  second_opinion: SecondOpinion | null;
}

export interface DataHealth {
  players_fetched_at: number;
  projections_fetched_at: number;
  weekly_fetched_at: number;
  board_size: number;
  warnings: Array<string>;
  poll_last_success_at: number | null;
  poll_consecutive_failures: number;
  poll_last_error: string | null;
  second_opinion_loaded_at: number | null;
}

export interface DraftStatus {
  draft_id: string;
  status: string;
  teams: number;
  rounds: number;
  pick_timer: number | null;
  current_pick: number;
  current_round: number;
  on_clock_slot: number;
  on_clock_name: string | null;
  my_slot: number | null;
  is_my_pick: boolean;
  picks_until_mine: number | null;
  my_next_picks: Array<number>;
  total_picks_made: number;
  manual_picks_active: boolean;
  paused: boolean;
  clock_deadline_ms: number | null;
  pick_slot_overrides: Record<string, number>;
  keeper_picks: Array<number>;
  is_auction: boolean;
  seat_note: string | null;
}

export interface LeagueSummary {
  league_id: string;
  platform: Platform;
  name: string;
  season: string;
  total_rosters: number;
  roster_positions: Array<string>;
  draftable_positions: Array<string>;
  scoring_settings: Record<string, number>;
}

export interface PickPrice {
  round: number;
  points: number;
  example: string | null;
}

export type Platform = "sleeper" | "yahoo";

export interface PositionRun {
  position: string;
  count: number;
  window: number;
}

export interface RecentPick {
  pick_no: number;
  round: number;
  slot: number;
  slot_name: string | null;
  player_id: string;
  name: string;
  position: string;
  team: string | null;
}

export interface Recommendation {
  mode: string;
  player_id: string;
  name: string;
  position: string;
  team: string | null;
  points: number;
  vorp: number;
  tier: number;
  adp: number | null;
  survival_next: number | null;
  score: number;
  reasons: Array<string>;
}

export interface SecondOpinion {
  positional_rank: number;
  overall_rank: number;
  source: string;
}

export interface TeamProjection {
  slot: number;
  name: string | null;
  starters: number;
  bench: number;
  holes: Array<string>;
  rank: number;
  title_odds: number | null;
  is_mine: boolean;
}

export interface TeamRoster {
  slot: number;
  display_name: string | null;
  players: Array<RosterEntry>;
  open_starters: Array<[string, number]>;
}

export interface RosterEntry {
  player_id: string;
  name: string;
  position: string;
  team: string | null;
  pick_no: number;
  round: number;
  is_keeper: boolean;
}

export interface TierAlert {
  position: string;
  tier: number;
  players_left: number;
}
