//! Generate the draft DTO graph from Rust syntax, never hand-maintained TS.
//! Unsupported serde representations fail closed instead of guessing a type.
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
use syn::{Fields, GenericArgument, Item, ItemEnum, ItemStruct, PathArguments, Type};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

#[derive(Default)]
struct Contract {
    structs: BTreeMap<String, ItemStruct>,
    enums: BTreeMap<String, ItemEnum>,
    versions: BTreeMap<String, String>,
}

impl Contract {
    fn read(&mut self, source: &str) -> Result<()> {
        for item in syn::parse_file(source)?.items {
            match item {
                Item::Enum(item) => {
                    self.enums.insert(item.ident.to_string(), item);
                }
                Item::Struct(item) => {
                    self.structs.insert(item.ident.to_string(), item);
                }
                Item::Const(item) if item.ident.to_string().ends_with("SCHEMA_VERSION") => {
                    let syn::Expr::Lit(lit) = *item.expr else {
                        return Err("schema version must be a literal".into());
                    };
                    let syn::Lit::Str(value) = lit.lit else {
                        return Err("schema version must be a string".into());
                    };
                    self.versions.insert(item.ident.to_string(), value.value());
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn render(&self) -> Result<String> {
        let mut output = String::from("// Generated by npm run generate:contract. Do not edit.\n");
        for (name, value) in &self.versions {
            output.push_str(&format!("export const {name} = {value:?};\n"));
        }
        let mut pending = BTreeSet::from(["DraftView".to_string()]);
        let mut emitted = BTreeSet::new();
        while let Some(name) = pending.pop_first() {
            if !emitted.insert(name.clone()) {
                continue;
            }
            if let Some(item) = self.enums.get(&name) {
                let mut lowercase = false;
                for attr in &item.attrs {
                    if attr.path().is_ident("serde") {
                        attr.parse_nested_meta(|meta| {
                            if meta.path.is_ident("rename_all") {
                                let value: syn::LitStr = meta.value()?.parse()?;
                                if value.value() == "lowercase" {
                                    lowercase = true;
                                    return Ok(());
                                }
                            }
                            Err(meta.error("unsupported enum wire representation"))
                        })?;
                    }
                }
                let variants = item
                    .variants
                    .iter()
                    .map(|variant| {
                        if !matches!(variant.fields, Fields::Unit)
                            || variant.attrs.iter().any(|a| a.path().is_ident("serde"))
                        {
                            return Err("unsupported enum variant".into());
                        }
                        let label = variant.ident.to_string();
                        Ok(format!(
                            "{:?}",
                            if lowercase {
                                label.to_lowercase()
                            } else {
                                label
                            }
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?;
                output.push_str(&format!(
                    "\nexport type {name} = {};\n",
                    variants.join(" | ")
                ));
                continue;
            }
            let item = self
                .structs
                .get(&name)
                .ok_or(format!("unknown wire type {name}"))?;
            if item.attrs.iter().any(|a| a.path().is_ident("serde")) {
                return Err(format!("unsupported container serde representation on {name}").into());
            }
            let Fields::Named(fields) = &item.fields else {
                return Err(format!("unsupported tuple/unit struct {name}").into());
            };
            let mut bases = Vec::new();
            let mut lines = Vec::new();
            for field in &fields.named {
                let mut skip = false;
                let mut flatten = false;
                for attr in &field.attrs {
                    if attr.path().is_ident("serde") {
                        attr.parse_nested_meta(|meta| {
                            if meta.path.is_ident("skip") || meta.path.is_ident("skip_serializing")
                            {
                                skip = true;
                            } else if meta.path.is_ident("flatten") {
                                flatten = true;
                            } else {
                                return Err(meta.error(
                                    "unsupported wire attribute; extend generator explicitly",
                                ));
                            }
                            Ok(())
                        })?;
                    }
                }
                if skip {
                    continue;
                }
                let ty = ts_type(&field.ty, &mut pending)?;
                if flatten {
                    if !self.structs.contains_key(&ty) {
                        return Err("flatten requires a named struct".into());
                    }
                    bases.push(ty);
                } else {
                    let key = field.ident.as_ref().ok_or("unnamed field")?;
                    lines.push(format!("  {key}: {ty};\n"));
                }
            }
            let extends = if bases.is_empty() {
                String::new()
            } else {
                format!(" extends {}", bases.join(", "))
            };
            output.push_str(&format!(
                "\nexport interface {name}{extends} {{\n{}}}\n",
                lines.join("")
            ));
        }
        Ok(output)
    }
}

fn ts_type(ty: &Type, pending: &mut BTreeSet<String>) -> Result<String> {
    if let Type::Tuple(tuple) = ty {
        return Ok(format!(
            "[{}]",
            tuple
                .elems
                .iter()
                .map(|t| ts_type(t, pending))
                .collect::<Result<Vec<_>>>()?
                .join(", ")
        ));
    }
    let Type::Path(path) = ty else {
        return Err("unsupported wire type".into());
    };
    let segment = path.path.segments.last().ok_or("empty type path")?;
    let name = segment.ident.to_string();
    let args = match &segment.arguments {
        PathArguments::None => Vec::new(),
        PathArguments::AngleBracketed(args) => args
            .args
            .iter()
            .map(|a| {
                let GenericArgument::Type(t) = a else {
                    return Err("unsupported generic argument".into());
                };
                ts_type(t, pending)
            })
            .collect::<Result<Vec<_>>>()?,
        _ => return Err("unsupported type arguments".into()),
    };
    Ok(match (name.as_str(), args.as_slice()) {
        ("String", []) => "string".into(),
        ("bool", []) => "boolean".into(),
        (
            "u8" | "u16" | "u32" | "u64" | "usize" | "i8" | "i16" | "i32" | "i64" | "isize" | "f32"
            | "f64",
            [],
        ) => "number".into(),
        ("Option", [inner]) => format!("{inner} | null"),
        ("Vec", [inner]) => format!("Array<{inner}>"),
        ("HashMap" | "BTreeMap", [key, value]) if key == "string" || key == "number" => {
            format!("Record<string, {value}>")
        }
        (_, []) => {
            pending.insert(name.clone());
            name
        }
        _ => return Err(format!("unsupported generic type {name}").into()),
    })
}

fn main() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut contract = Contract::default();
    for file in [
        "view_types.rs",
        "board.rs",
        "draft.rs",
        "recommend.rs",
        "pick_value.rs",
        "second_opinion.rs",
        "draft_projection.rs",
        "season.rs",
    ] {
        contract.read(&std::fs::read_to_string(root.join("src").join(file))?)?;
    }
    print!("{}", contract.render()?);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn render(source: &str) -> Result<String> {
        let mut contract = Contract::default();
        contract.read(source)?;
        contract.render()
    }

    #[test]
    fn required_nullable_flattened_and_skipped_fields_match_serde() {
        let output = render(
            r#"
            pub const DRAFT_SCHEMA_VERSION: &str = "test";
            struct DraftView { rows: Vec<Row>, maybe: Option<Row>, pairs: Vec<(String, u32)> }
            struct Row { #[serde(flatten)] base: Base, #[serde(skip)] secret: String }
            struct Base { id: String }
        "#,
        )
        .unwrap();
        assert!(output.contains("rows: Array<Row>"));
        assert!(output.contains("maybe: Row | null"));
        assert!(!output.contains("maybe?"));
        assert!(output.contains("pairs: Array<[string, number]>"));
        assert!(output.contains("Row extends Base"));
        assert!(!output.contains("secret"));
        assert!(output.contains("DRAFT_SCHEMA_VERSION = \"test\""));
    }

    #[test]
    fn enum_values_follow_the_serialized_spelling() {
        let output = render(
            r#"
            struct DraftView { platform: Platform }
            #[serde(rename_all = "lowercase")]
            enum Platform { Sleeper, Yahoo }
        "#,
        )
        .unwrap();
        assert!(output.contains("export type Platform = \"sleeper\" | \"yahoo\";"));
    }

    #[test]
    fn unsupported_serialization_cannot_silently_generate_wrong_types() {
        assert!(render("struct DraftView { #[serde(skip_serializing_if = \"Option::is_none\")] value: Option<String> }").is_err());
        assert!(render(
            "#[serde(rename_all = \"camelCase\")] struct DraftView { some_value: String }"
        )
        .is_err());
        assert!(render("struct DraftView { missing: Unknown }").is_err());
    }
}
